language: node_js
node_js:
  - '10.15.3'

script:
  - npm run build && npm run lint

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_0be7659e51c5_key -iv $encrypted_0be7659e51c5_iv -in id_ed25519_koneko-website.enc -out /home/travis/.ssh/id_ed25519 -d;
      chmod 600 ~/.ssh/id_ed25519;
      echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config;
      git config --global user.email "gedorinku@yahoo.co.jp";
      git config --global user.name "gedorinku";
      git clone git@github.com:ProgrammingLab/koneko-website.git;
      cd koneko-website;
      rm -rf static/;
      cp -aR ../dist/* .;
      git add --all;
      git commit -m "built by Travis CI JOB #$TRAVIS_JOB_NUMBER";
      git push origin master;
    fi

notifications:
  email:
    on_success: never
    on_failure: always

